name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout Code from Repo
      uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Install SonarQube Scanner
    - name: Install SonarQube Scanner
      run: |
        curl -sLO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        echo "$(pwd)/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

    # Run SonarQube Scan
    - name: Run SonarQube Analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=Tictac-App \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # Setup AWS credentials
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Build Docker image using short SHA tag
    - name: Build Docker Image
      id: build_image
      run: |
        AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
        SHORT_SHA=${GITHUB_SHA::7}
        IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/tictac:$SHORT_SHA"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        docker build -t $IMAGE .

    # Trivy Scan of Docker Image
    - name: Scan the Docker Image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE }}
        format: sarif
        output: docker-result.sarif
        ignore-unfixed: false
        severity: HIGH,CRITICAL
        exit-code: "0"

    # Upload Trivy results to Github
    - name: Upload Trivy Output
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: docker-result.sarif

    # Push only when scan
    - name: Push Docker Image
      if: success()
      run: |
        echo "Pushing Docker Image: $IMAGE"
        docker push $IMAGE
    - name: Stetup Eks Kubectl
      run: |
        aws eks update-kubeconfig --region eu-north-1 --name ${{
          secrets.EKS_NAME
          }}
