name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login to Nexus
      run: |
        docker login 16.170.231.163:5000 -u ${{ secrets.NEXUS_USER }} -p ${{ secrets.NEXUS_PASS }}

    - name: Build Docker Image
      run: |
        docker build -t 16.170.231.163:5000/tictac-app:latest .

    - name: Run Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '16.170.231.163:5000/tictac-app:latest'
        severity: HIGH,CRITICAL
        exit-code: '0'

    - name: Push Docker Image to Nexus
      run: |
        docker push 16.170.231.163:5000/tictac-app:latest
