name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
    # 1Ô∏è‚É£ Checkout code
    - name: Checkout Code from Repo
      uses: actions/checkout@v2

    # 2Ô∏è‚É£ Setup Node.js
    - name: Setup Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # 3Ô∏è‚É£ Install dependencies
    - name: Install Dependencies
      run: npm install

    # 4Ô∏è‚É£ Install SonarQube Scanner
    - name: Install SonarQube Scanner
      run: |
        curl -sLO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        echo "$(pwd)/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

    # 5Ô∏è‚É£ Run SonarQube Analysis
    - name: Run SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=Tictac-App \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # 6Ô∏è‚É£ Setup AWS credentials
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # 7Ô∏è‚É£ Login to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # 8Ô∏è‚É£ Build Docker image using short SHA tag
    - name: Build Docker Image
      id: build_image
      run: |
        AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
        SHORT_SHA=${GITHUB_SHA::7}
        IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/tictac:$SHORT_SHA"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        docker build -t $IMAGE .

    # 9Ô∏è‚É£ Scan Docker image with Trivy
    - name: Scan the Docker Image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE }}
        format: sarif
        output: docker-result.sarif
        ignore-unfixed: false
        severity: HIGH,CRITICAL
        exit-code: "0"

    # üîü Upload Trivy results to GitHub
    - name: Upload Trivy Output
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: docker-result.sarif

    # 11Ô∏è‚É£ Push Docker image to ECR
    - name: Push Docker Image
      if: success()
      run: |
        echo "Pushing Docker Image: $IMAGE"
        docker push $IMAGE

    # ------------------------------
    # Configure EKS (eu-north-1)
    # ------------------------------

    - name: Setup AWS Credentials (EKS Region)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # Configure kubectl for EKS
    - name: Create CA Certificate File
      run: |
        echo "${{ secrets.EKS_CA_DATA }}" | base64 --decode > ca.crt

    - name: Configure kubectl for EKS
      run: |
        kubectl config set-cluster ${{ secrets.EKS_NAME }} \
        --server=${{ secrets.EKS_ENDPOINT }} \
        --certificate-authority=ca.crt

        kubectl config set-credentials github-user \
        --token=${{ secrets.EKS_TOKEN }}

        kubectl config set-context ${{ secrets.EKS_NAME }} \
         --cluster=${{ secrets.EKS_NAME }} \
         --user=github-user \
         --namespace=default

        kubectl config use-context ${{ secrets.EKS_NAME }}

    # 12Ô∏è‚É£ Deploy to kubernetes
    - name: Deploy to Kubernetes
      env:
        IMAGE: ${{ env.IMAGE }}
      run: |
        echo "Deploying image: $IMAGE to EKS cluster: ${{ secrets.EKS_NAME }}"

        kubectl set image deployment/tictac-app \
          tictac=$IMAGE -n webapps --record

        echo "Waiting for rollout to finish..."
        kubectl rollout status deployment/tictac-app -n webapps
